
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Rules.Processor.Api
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
      
  /// <summary>Represents the "Rule" template.</summary>
  public partial class Rule : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{D9BDF22F-6E17-47F3-AB64-49C717BA92DA}");

    public Rule(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID RuleName = ID.Parse("{45CF9130-802A-41BE-B3EB-C02F657DCC2E}");

      public static readonly ID Rules = ID.Parse("{908EF45D-4940-4B6A-857D-3739BA4ACF8F}");

    }
    
    /// <summary>Gets or sets the "Name" field.</summary>
    public string RuleName 
    {
      get 
      {
        return this.InnerItem[FieldIds.RuleName];
      }
      set
      {
        this.InnerItem[FieldIds.RuleName] = value;
      }
    }
  
    /// <summary>Gets or sets the "Rule" field.</summary>
    public string Rules {
      get 
      {
        return this.InnerItem[FieldIds.Rules];
      }
      set 
      {
        this.InnerItem[FieldIds.Rules] = value;
      }
    }
  
    public static Rule Create(Item item) 
    {
      return new Rule(item);
    }

    public static implicit operator Item (Rule item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator Rule(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
